#!/bin/sh
if [ -f /tmp/GlamourAuraLime/skin.xml ]; then
	rm -rf /usr/share/enigma2/GlamourAuraLime/
	mv /tmp/GlamourAuraLime /usr/share/enigma2/
fi
echo "                                                                                "
echo "Glamour Aura Lime main files installed, now linking common files to main skin..." 
cp -Rs /usr/share/enigma2/GlamourAuraFHD/* /usr/share/enigma2/GlamourAuraLime 2>/dev/null
echo "                                                                     "
echo "Glamour Aura Lime skin is now successfully installed on your receiver"
echo "                         Enjoy!!!                                    "
