#!/bin/sh
if [ -f /tmp/GlamourAuraLime/skin.xml ]; then
  rm -rf /usr/share/enigma2/GlamourAuraLime/
  mv /tmp/GlamourAuraLime /usr/share/enigma2/
fi
echo "                                                                                 "
echo "Glamour Aura Lime skin for OpenPLI is now successfully installed in your receiver"
echo "                             Enjoy!!!                                            "
