#!/bin/sh
rm -rf /usr/share/enigma2/GlamourAuraLime
echo "                                                                   "
echo "Glamour Aura Lime skin was successfully removed from your receiver."