#!/bin/sh
echo "                             *******                          "
echo "                       ******       *****                     "
echo "                  ****                   ****                 "
echo "               ***                            ***             "
echo "             **     GLAMOUR AURA LIME SKIN       **           "
echo "                     a skin by MCelliotG                      "
echo "                                                              "
echo "                                                              "
echo "             *********    DISCLAIMER      *********           "
echo "Glamour Aura Lime skin requires a minimal CPU @ 751 Mhz.      "
echo "Glamour Aura Lime is NOT guaranteed to work on slower or older receivers."
echo "                                             "
echo "                                             "
echo "                                             "
echo "                                             "
echo "Checking if a previous version of Glamour Aura Lime skin is installed..."
if [ -f /usr/share/enigma2/GlamourAuraLime/skin.xml ]; then
    cp -R /usr/share/enigma2/GlamourAuraLime/ /tmp
    rm -rf /usr/share/enigma2/GlamourAuraLime
    echo "                                            "
    echo "Previous Glamour Aura Lime skin installation"
    echo "    was found and removed successfully!     "
    echo "                                            "
fi
echo "                                                "
echo "Glamour Aura Lime skin is now being installed..."
echo "                                                "
