#!/bin/sh
echo "                                                              "
echo "Glamour Aura Lime skin is now being removed from your receiver"
echo "                                                              "
